name: Space Travel Comparison
on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Wikidata Mismatch Finder Access Token.'
  schedule:
    - cron: '0 0 10 * *'

jobs:
  compare:
    runs-on: ubuntu-latest
    container: ghcr.io/fusion-jena/abecto:v2.0.0
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Run ABECTO Space Travel Comparison
        run: abecto --trig space-travel-comparison-result.trig space-travel-comparison.trig
      - name: Generate Wikidata Mismatch Finder report
        run: abecto --loadOnly --export wdMismatchFinder=space-travel-comparison-wdMismatchFinder.csv space-travel-comparison-result.trig
      - name: Upload Wikidata Mismatch Finder report
        if: ${{ github.event.inputs.token != null || github.event.schedule != null }}
        run: |
          apt update && apt install -y curl
          curl -X POST "https://mismatch-finder.toolforge.org/api/imports" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ github.event.inputs.token || secrets.MISMATCH_FINDER_TOKEN }}" \
            -F "mismatch_file=@space-travel-comparison-wdMismatchFinder.csv" \
            -F "description=Mismatches found by a comparison of space travel data from Wikidata and DBpedia using ABECTO. See: https://github.com/fusion-jena/abecto-space-travel-comparison" \
            -F "external_source=DBpedia" \
            -F "external_source_url=http://dbpedia.org/" \
            -F "expires=$(date -d "-9 days 1 month" +"%Y-%m-10")"
      - name: Archive Wikidata Mismatch Finder report
        uses: actions/upload-artifact@v3
        with:
          name: Wikidata Mismatch Finder report
          path: space-travel-comparison-wdMismatchFinder.csv
